# Generated by Django 5.1.3 on 2024-11-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_pharmageap", "0002_analyseprediction_parametreglobal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pharmacie",
            name="grossiste_principal",
        ),
    ]
