# Generated by Django 5.1.3 on 2024-11-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_pharmageap", "0004_pharmacie_user_alter_pharmacie_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacie",
            name="date_inscription",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
