# Generated by Django 5.1.3 on 2024-11-28 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grossiste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("delai_livraison", models.CharField(max_length=50)),
                (
                    "commande_minimum",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("evaluation", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="StatistiquesCommandes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_commandes", models.PositiveIntegerField()),
                ("livraisons_en_attente", models.PositiveIntegerField()),
                (
                    "depenses_mensuelles",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("tendances_prix", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ProduitGrossiste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField()),
                (
                    "grossiste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="app_pharmageap.grossiste",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=50,
                    ),
                ),
                (
                    "grossiste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="app_pharmageap.grossiste",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="app_pharmageap.produitgrossiste",
                    ),
                ),
            ],
        ),
    ]
